export const PostData = [
  {
    id: 1,
    profileImg: '/col-3-img.png',
    profileName: 'Luis Shawn',
    time: '3rd jun at 10:53 pm',
    favouritePlace:
      'One of the best place i heaven ever seen. Turkey is my favourite place now',
    img: ['/post-1.svg', '/post-2.svg', '/post-3.svg'],
    isLike: false,
    likes: 25,
    comments: [
      {
        name: 'Luis Shawn',
        comment: 'nice place',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'is it Turkey?',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'send these photos personally',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'nice picture',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'looking good',
        time: '2',
        likes: 5,
        reply: 3,
      },
    ],
  },
  {
    id: 2,
    profileImg: '/col-3-img.png',
    profileName: 'Prachi Desoi',
    time: '3rd jun at 10:53 pm',
    favouritePlace: 'Summer Vacation 2021..',
    img: ['/post-1.svg', '/post-2.svg', '/post-3.svg'],
    isLike: false,
    likes: 25,
    comments: [
      {
        name: 'Luis Shawn',
        comment: 'nice place',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'is it Turkey?',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'send these photos personally',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'nice picture',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'looking good',
        time: '2',
        likes: 5,
        reply: 3,
      },
    ],
  },
  {
    id: 3,
    profileImg: '/col-3-img.png',
    profileName: 'Paul Wesley',
    time: '3rd jun at 10:53 pm',
    favouritePlace:
      'One of the best place i heaven ever seen. Turkey is my favourite place now',
    img: ['/video.mp4'],
    isLike: false,
    likes: 25,
    comments: [
      {
        name: 'Luis Shawn',
        comment: 'nice place',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'is it Turkey?',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'send these photos personally',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'nice picture',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'looking good',
        time: '2',
        likes: 5,
        reply: 3,
      },
    ],
  },
  {
    id: 4,
    profileImg: '/col-3-img.png',
    profileName: 'Prachi Desoi',
    time: '3rd jun at 10:53 pm',
    favouritePlace:
      'One of the best place i heaven ever seen. Turkey is my favourite place now',
    img: ['/post-1.svg', '/post-2.svg', '/post-3.svg'],
    isLike: false,
    likes: 25,
    comments: [
      {
        name: 'Luis Shawn',
        comment: 'nice place',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'is it Turkey?',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'send these photos personally',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'nice picture',
        time: '2',
        likes: 5,
        reply: 3,
      },
      {
        name: 'Luis Shawn',
        comment: 'looking good',
        time: '2',
        likes: 5,
        reply: 3,
      },
    ],
  },
];
